config/routes.rb
Rails.application.routes.draw do
  get "/first", to: "site#first", as: :first_page
  get "/second", to: "site#second", as: :second_page
  post "/third", to: "site#third", as: :third_page

  get "/fourth", to: "site#fourth", as: :fourth_page
  post "/fifth", to: "site#fifth", as: :fifth_page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController 

    def first
    end

    def second
    end 

    def third
        respond_to do |format|
            format.html { render :third_page }
            format.turbo_stream { head  Turbo::StreamsChannel.broadcast_update_to(
                "event_when_button_clicked",
                target: "content",
                partial: "site/dynamic_content",
                locals: {
                  my_value: 1000
                }
            )}
          end
    end

    def fourth
    end

    def fifth
      render turbo_stream: turbo_stream.update('hello_frame', partial: 'ajax_template')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbohack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/site/_ajax_template.html.erb
Hi, it's <%= Time.now %>.

<%= params["values_to_pass_to_controller"] ? params["values_to_pass_to_controller"] : ""  %>

app/views/site/_dynamic_content.html.erb
<p>Hi</p>

<p><%= defined?(my_value) && my_value.present?  ? my_value : 10  %></p>

app/views/site/_streamed_stuff.html.erb
<div class="py-4 mb-8 border text-center shadow-lg font-bold bg-white">
  <%= Time.now.strftime("%d %b %Y, %H:%M:%S") %>
</div>

  <p class="my-4">Lorem ipsum dolor</p>
<p><%= defined?(my_value) && my_value.present?  ? my_value : 10  %></p>

app/views/site/first.html.erb
<%= turbo_stream_from "mystr" %>

<div class="my-8 w-full mx-auto" id="content">
  <%= render "streamed_stuff" %>
</div>

app/views/site/fourth.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turbo Frame Example</title>
  <style>
    body {
      margin: 10%
    }
  </style>
</head>
<body>

<%= button_to 'Click me', fifth_page_path(values_to_pass_to_controller: "Value passed from event"), remote: true %>

<%= turbo_frame_tag 'hello_frame' do %>
  <%= render partial: 'ajax_template' %>
<%end %>
</body>

</html>

app/views/site/second.html.erb
<%= turbo_stream_from "event_when_button_clicked" %>

<%= button_to "Click me", third_page_path, remote: true, class: "turbo-frame" %>

<div class="my-8 w-full mx-auto" id="content">
  <%= render "dynamic_content" %>
</div>